### ISSUE TITLE
Erro no cli: "SyntaxError: Unexpected token u"

### ISSUE THREAD

**Issue by matepaiva** [cauealves/mega-sena-cli#1]
$ mega-sena 05 06 12 19 30 60
undefined:1
undefined
^

SyntaxError: Unexpected token u
    at Object.parse (native)
    at /usr/local/lib/node_modules/mega-sena-cli/cli.js:30:22
    at ReadFileContext.callback (/usr/local/lib/node_modules/mega-sena-cli/node_modules/jsonfile/index.js:25:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete](fs.js:324:13)

**Comment by andrevandal** [comment]
Testei usando v4.2.6 e retornou:

```
⬢  ~  mega-sena 05 06 12 19 30 10 
undefined:1
undefined
^

SyntaxError: Unexpected token u
    at Object.parse (native)
    at /home/derevandal/.nvm/versions/node/v4.2.6/lib/node_modules/mega-sena-cli/cli.js:30:22
    at ReadFileContext.callback (/home/derevandal/.nvm/versions/node/v4.2.6/lib/node_modules/mega-sena-cli/node_modules/jsonfile/index.js:25:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
```

Já com a v6.2.1

```
⬢  ~  mega-sena 05 06 12 19 30 10  
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at /home/derevandal/.nvm/versions/node/v6.2.1/lib/node_modules/mega-sena-cli/cli.js:30:22
    at ReadFileContext.callback (/home/derevandal/.nvm/versions/node/v6.2.1/lib/node_modules/mega-sena-cli/node_modules/jsonfile/index.js:25:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)
```

**Comment by caueops** [comment]
Poderiam tentar atualizar, por gentileza?

`npm update -g mega-sena-cli`

Depois disso, tentem novamente e vê se continua acontecendo.

**Comment by caueops** [comment]
cc @matepaiva @deregudegu

**Comment by matepaiva** [comment]
Aqui continua igual.

Mate Paiva
61 9357-5533

2016-06-07 12:37 GMT-03:00 Cauê Alves notifications@github.com:

**Comment by caueops** [comment]
Estou utilizando a seguinte stack
- `node v4.2.2`
- `npm v2.14.7`

E está funcionando perfeitamente, veja:

![captura de tela 2016-06-07 as 13 09 15](https://cloud.githubusercontent.com/assets/7065285/15865437/15559698-2cb1-11e6-80f7-770f945b8551.png)

Quando você executa `mega-sena --version` qual é o retorno?

**Comment by matepaiva** [comment]
0.1.1 é o retorno

Mate Paiva
61 9357-5533

Em 7 de junho de 2016 13:10, Cauê Alves notifications@github.com escreveu:

**Comment by caueops** [comment]
Atualmente a versão está na `0.1.2`, depois tenta fazer o update novamente.

Enquanto isso vou investigar um pouco mais.

**Comment by matepaiva** [comment]
mate-paiva@leFenix:~$ mega-sena --version
0.1.2
mate-paiva@leFenix:~$ mega-sena 10 20 30 40 50 60
undefined:1
undefined
^

SyntaxError: Unexpected token u
    at Object.parse (native)
    at /usr/local/lib/node_modules/mega-sena-cli/cli.js:30:22
    at ReadFileContext.callback
(/usr/local/lib/node_modules/mega-sena-cli/node_modules/jsonfile/index.js:25:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete](fs.js:324:13)

mate-paiva@leFenix:~$ npm -v
3.8.6
mate-paiva@leFenix:~$ node -v
v5.8.0

Mate Paiva
61 9357-5533

2016-06-07 13:17 GMT-03:00 Cauê Alves notifications@github.com:

**Comment by caueops** [comment]
@matepaiva Obrigado pelas informações. Vou investigar mais tarde!

**Comment by matepaiva** [comment]
precisando só chamar!

Mate Paiva
61 9357-5533

2016-06-07 13:33 GMT-03:00 Cauê Alves notifications@github.com:

**Comment by caueops** [comment]
Lancei uma nova versão para tentar corrigir este problema!

Tenta fazer um novo update, a versão atual é: `0.1.3`

**Comment by matepaiva** [comment]
Volto pro notebook de noite e faço o teste :)

**Comment by caueops** [comment]
@matepaiva Conseguiu dar uma olhada?

**Comment by matepaiva** [comment]
Ainda não cheguei em casa, rs. Mas chegando eu olho. Até meia noite.

**Comment by caueops** [comment]
Valeu! Estarei aguardando feedback.

**Comment by matepaiva** [comment]
Funcionando!!!! :D

Mate Paiva
61 9357-5533

2016-06-07 23:00 GMT-03:00 Cauê Alves notifications@github.com:

**Comment by caueops** [comment]
Obrigado pela ajuda @matepaiva \o

**Comment by caueops** [comment]
@deregudegu É só realizar o update do cli que irá funcionar normalmente.
