### ISSUE TITLE
Emojis não funcionam em plataforma Windows

### ISSUE THREAD

**Issue by AdrianoCahete** [cauealves/mega-sena-cli#4]
Olhei no código e vi que são emojis.

Stack aqui é o Windows10, CLI é o PowerShell:
![megasena](https://cloud.githubusercontent.com/assets/37474/15876117/d046edb4-2ce1-11e6-8bc0-943d06c3f78f.PNG)

**Comment by caueops** [comment]
Muito obrigado pro enviar essa issue. Assim que eu tiver um tempo vou dar uma olhada.
E sinta-se à vontade para resolve-la e abrir um pull request :)

**Comment by AdrianoCahete** [comment]
> E sinta-se à vontade para resolve-la e abrir um pull request :)    

Feito! :)

Só não tive tempo de ajeitar os testes, então não deve passar no Travis. :(
