### ISSUE TITLE
Verificar rodadas duplicadas

### ISSUE THREAD

**Issue by wmarquardt** [cauealves/mega-sena-cli#6]
Atualmente está verificando apenas rodada única.

Supondo que determinada sequência foi sorteada 2x, irá aparecer somente uma.

**Comment by caueops** [comment]
Fala @wmarquardt, obrigado pela issue.

Acredito que possa ser discutido, até pra entender a probabilidade disso acontecer. Acha que estaticamente isso é possível?

**Comment by wmarquardt** [comment]
Realmente @cauealves, é praticamente impossível. Acredito que seja a mesma probabilidade de alguém acertar o prêmio. 1 em 50M.

Talvez seja útil no caso da outra issue que eu criei, para verificar se já foi quadra ou quina. Acredito que nesse caso as probabilidades sejam maiores.

**Comment by caueops** [comment]
Concordo contigo. Se quiser realizar um fork e enviar uma proposta p/ outra issue, fique à vontade :)
